version: '3.2'

networks:
  kafka-network:
    name: kafka-network

services:
  delivery-service:
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    networks:
      - kafka-network